#!/bin/bash

# gitfdiff <commit> [commit] <file>

if [ $# -eq 2 -o $# -eq 3 ]; then
	if [ $# -eq 2 ]; then
		commit1=$1
		commit2=HEAD
		file=$2
	else
		commit1=$1
		commit2=$2
		file=$3
	fi
	#echo $commit1, $commit2, $file
	# step 1, get version 1
	git show $commit1:$file > "$file"_d
	# step 2, format it.
	astyle -q "$file"_d
	# step 3, add it to git temporarily.
	git add "$file"_d
	# step 4, get version 2
	git show $commit2:$file > "$file"_d
	# step 5, format it.
	astyle -q "$file"_d
	# step 6, use git diff
	git diff "$file"_d
	# step 7, reset
	git reset -q "$file"_d
	# remove the temp file
	rm "$file"_d
else
	echo "Usage gitfdiff <commit> [commit] file"
fi
